# Configuration

decompile:
    tmp_dir: /tmp/arecu_tmp/
    lib_path: /usr/local/bin/arecu_dir/

screenshot:

    # File name: <file_name>_{num}.png
    # Ex. ss_001.png, ss_002.png, ...
    file_name: ss

    # A directory for temporarily saving images in Android devices
    # Default: /sdcard/Download/
    tmp_dir: /sdcard/Download/
