#!/bin/bash

# Argument arror checking.
if [ ! "$#" -eq "1" ]
then
	echo "Error, Please designate dex file."
	exit 2
fi

echo "--- Dex to Jar ---"
d2j-dex2jar.sh $1
echo "--- Unzip jar file ---"
unzip classes-dex2jar.jar -d result
echo "--- JavaDecompiler ---"
jd-cli result
echo "Done."

exit 0
